packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@firebase/util': true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  # If any future packages prompt, add them here.
